# syntax=docker/dockerfile:1

# https://adoptium.net/temurin/releases/

# https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u352-b08/OpenJDK8U-debugimage_x64_alpine-linux_hotspot_8u352b08.tar.gz
# https://github.com/adoptium/temurin8-binaries/releases/download/jdk-8u352-b08/OpenJDK8U-jre_x64_alpine-linux_hotspot_8u352b08.tar.gz

# https://github.com/adoptium/temurin19-binaries/releases/download/jdk-19.0.1%2B10/OpenJDK19U-jre_x64_linux_hotspot_19.0.1_10.tar.gz

# Start from Ubuntu
FROM ghcr.io/viral32111/ubuntu:22.10

# Configure the Java version & directory
ARG JAVA_VERSION=19.0.1+10 \
	JAVA_DIRECTORY=/opt/java

# Download Eclipse Temurin's Java from Adoptium
RUN apt-get update && \
	apt-get install --no-install-recommends --yes wget && \
	mkdir --verbose --parents ${JAVA_DIRECTORY} && \
	export JAVA_VERSION_MAJOR=$([[ "${JAVA_VERSION}" == 8u* ]] && echo "${JAVA_VERSION}" | cut -d u -f 1 || echo "${JAVA_VERSION}" | cut -d . -f 1) && \
	export JAVA_VERSION_FILE=$([[ "${JAVA_VERSION}" == 8u* ]] && echo "${JAVA_VERSION}" | sed 's/-//' || echo "${JAVA_VERSION}" | sed -E 's/\+/_/') && \
	export JAVA_DOWNLOAD_TYPE=$([ "${JAVA_VERSION_MAJOR}" == '16' ] && echo 'jdk' || echo 'jre') && \
	export GITHUB_RELEASE_TITLE=$([ "${JAVA_VERSION_MAJOR}" == '8' ] && echo "jdk${JAVA_VERSION}" || echo "jdk-${JAVA_VERSION}") && \
	wget --no-hsts --progress dot:mega --output-document /tmp/java.tar.gz https://github.com/adoptium/temurin${JAVA_VERSION_MAJOR}-binaries/releases/download/${GITHUB_RELEASE_TITLE}/OpenJDK${JAVA_VERSION_MAJOR}U-${JAVA_DOWNLOAD_TYPE}_x64_linux_hotspot_${JAVA_VERSION_FILE}.tar.gz 2>&1 && \
	tar --verbose --extract --no-same-owner --strip-components 1 \
		--exclude '*/NOTICE' \
		--exclude '*/LICENSE' \
		--exclude '*/THIRD_PARTY_README' \
		--exclude '*/ASSEMBLY_EXCEPTION' \
		--exclude '*/release' \
		--exclude '*/man' \
		--file /tmp/java.tar.gz --directory ${JAVA_DIRECTORY} && \
	apt-get purge --auto-remove --yes wget && \
	apt-get clean --yes && \
	rm --verbose --recursive \
		/tmp/java.tar.gz \
		/var/lib/apt/lists/*

# Add Java to the binaries & libraries paths & set its install directory
ENV PATH=${JAVA_DIRECTORY}/bin:$PATH \
	LD_LIBRARY_PATH=${JAVA_DIRECTORY}/lib:$LD_LIBRARY_PATH \
	JAVA_HOME=${JAVA_DIRECTORY}

# Run commands with Java
ENTRYPOINT [ "java" ]
