name: Cleanup

# This action deletes all of the untagged Docker images from the Container Registry.

on:
  push:
    paths:
      - '.github/workflows/cleanup.yml'
  schedule:
    - cron: '0 1 * * 0'
  workflow_run:
    workflows: [ 'Ubuntu', 'Alpine' ]
    types:
      - completed
  workflow_dispatch:

jobs:
  registry:
    name: Registry
    runs-on: ubuntu-22.04
    env:
      REGISTRY_NAME: ghcr.io
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete untagged Docker images
        uses: snok/container-retention-policy@v1
        with:
          image-names: ubuntu,alpine,java,dotnet,aspnetcore
          cut-off: 0 seconds ago UTC
          keep-at-least: 1
          untagged-only: true
          account-type: personal
          token: ${{ secrets.PAT_PACKAGES }}
