name: Cleanup

# This action deletes all untagged images older than 1 week.
# It runs every Sunday at 01:00, so after the Docker build workflow.

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  registry:
    name: Registry
    runs-on: ubuntu-22.04
    env:
      REGISTRY_NAME: ghcr.io
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete untagged images
        uses: snok/container-retention-policy@v1
        with:
          image-names: ubuntu,alpine,java
          cut-off: 1 week ago UTC
          keep-at-least: 1
          untagged-only: true
          account-type: personal
          token: ${{ secrets.GITHUB_TOKEN }}
