name: Docker

on:
  push:
    paths:
    - 'Context/**'
    - '**/Dockerfile'
    - '.dockerignore'
    - '.github/workflows/docker.yml'
    branches:
    - '**'
    tags:
    - '*.*.*'
  pull_request:
    branches:
    - '**'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

env:
  REGISTRY_NAME: ghcr.io
  PUBLISHER_WEBSITE: https://viral32111.com

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-22.04
    env:
      REGISTRY_IMAGE_NAME: ubuntu
      HUMAN_IMAGE_NAME: Ubuntu
    strategy:
      matrix:
        release: [ '20.04', '22.04', '22.10' ]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Fetch latest release version
        id: release
        run: |
          RELEASE_NAME=$(curl -s https://api.launchpad.net/1.0/ubuntu/series | jq -r '.entries[] | select( .version == "${{ matrix.release }}" ) | .name')
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_OUTPUT

          DATE_TODAY=$(date +'%Y-%m-%d')
          RELEASE_VERSION=$(curl -s https://api.launchpad.net/1.0/ubuntu/${RELEASE_NAME}/all_milestones | jq --arg today ${DATE_TODAY} -r '[ .entries[] | select( ( .name | endswith( "-updates" ) | not ) and .date_targeted <= $today ) ][ 0 ].name' | sed --regexp-extended 's/^ubuntu-//g')
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_OUTPUT

      - name: Download latest release archive
        run: |
          RELEASE_DOWNLOAD_URL="https://cdimage.ubuntu.com/ubuntu-base/releases/${{ matrix.release }}/release/ubuntu-base-${{ steps.release.outputs.RELEASE_VERSION }}-base-amd64.tar.gz"
          wget --output-document ./Context/base.tar.gz ${RELEASE_DOWNLOAD_URL}

      - name: Create metadata for Docker image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          flavor: latest=false
          images: ${{ env.REGISTRY_NAME }}/${{ github.repository_owner }}/${{ env.REGISTRY_IMAGE_NAME }}
          tags: type=raw,value=${{ matrix.release }}
          labels: |
            org.opencontainers.image.title=${{ env.HUMAN_IMAGE_NAME }} ${{ steps.release.outputs.RELEASE_VERSION }}
            org.opencontainers.image.description=My personal image for ${{ env.HUMAN_IMAGE_NAME }} ${{ steps.release.outputs.RELEASE_VERSION }}.
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=${{ matrix.release }}
            com.docker.extension.publisher-url=${{ env.PUBLISHER_WEBSITE }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
          file: ./Distributions/Ubuntu/Dockerfile
          context: ./Context
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          no-cache: true
          pull: true
          build-args: |
            UBUNTU_RELEASE_VERSION=${{ steps.release.outputs.RELEASE_VERSION }}
            UBUNTU_RELEASE_NAME=${{ steps.release.outputs.RELEASE_NAME }}

  alpine:
    name: Alpine
    runs-on: ubuntu-22.04
    env:
      REGISTRY_IMAGE_NAME: alpine
      HUMAN_IMAGE_NAME: Alpine
    strategy:
      matrix:
        release: [ '3.15', '3.16' ]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Download releases file
        run: |
          wget --output-document ./latest-releases.yaml https://dl-cdn.alpinelinux.org/alpine/v${{ matrix.release }}/releases/x86_64/latest-releases.yaml

      - name: Fetch latest release version
        id: release
        uses: mikefarah/yq@master
        with:
          cmd: yq '.[] | select( .flavor == "alpine-minirootfs" ) | .version' ./latest-releases.yaml

      - name: Download latest release archive
        run: |
          wget --output-document ./Context/base.tar.gz https://dl-cdn.alpinelinux.org/alpine/v${{ matrix.release }}/releases/x86_64/alpine-minirootfs-${{ steps.release.outputs.result }}-x86_64.tar.gz

      - name: Create metadata for Docker image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          flavor: latest=false
          images: ${{ env.REGISTRY_NAME }}/${{ github.repository_owner }}/${{ env.REGISTRY_IMAGE_NAME }}
          tags: type=raw,value=${{ matrix.release }}
          labels: |
            org.opencontainers.image.title=${{ env.HUMAN_IMAGE_NAME }} ${{ steps.release.outputs.result }}
            org.opencontainers.image.description=My personal image for ${{ env.HUMAN_IMAGE_NAME }} ${{ steps.release.outputs.result }}.
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=${{ matrix.release }}
            com.docker.extension.publisher-url=${{ env.PUBLISHER_WEBSITE }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
          file: ./Distributions/Alpine/Dockerfile
          context: ./Context
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          no-cache: true
          pull: true
          build-args: |
            ALPINE_BRANCH=${{ matrix.release }}
            ALPINE_VERSION=${{ steps.release.outputs.result }}

  java:
    name: Java
    runs-on: ubuntu-22.04
    needs: ubuntu
    env:
      REGISTRY_IMAGE_NAME: java
      HUMAN_IMAGE_NAME: Java
    strategy:
      matrix:
        version: [ '8', '11', '16', '17', '18', '19' ]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Fetch latest version
        id: version
        run: |
          VERSION_URL="https://api.github.com/repos/adoptium/temurin${{ matrix.version }}-binaries/releases/latest"
          VERSION_LATEST=$(curl --silent --header 'Accept: application/vnd.github+json' ${VERSION_URL} | jq -r .name | sed --regexp-extended 's/^jdk-?//g')
          echo "VERSION_LATEST=${VERSION_LATEST}" >> $GITHUB_OUTPUT

          VERSION_SCHEME=$(case ${{ matrix.version }} in 8) echo Legacy ;; 16) echo JDK ;; *) echo Modern ;; esac)
          echo "VERSION_SCHEME=${VERSION_SCHEME}" >> $GITHUB_OUTPUT

      - name: Create Metadata for Docker Image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          flavor: latest=false
          images: ${{ env.REGISTRY_NAME }}/${{ github.repository_owner }}/${{ env.REGISTRY_IMAGE_NAME }}
          tags: type=raw,value=${{ matrix.version }}
          labels: |
            org.opencontainers.image.title=${{ env.HUMAN_IMAGE_NAME }} ${{ steps.version.outputs.VERSION_LATEST }}
            org.opencontainers.image.description=My personal image for ${{ env.HUMAN_IMAGE_NAME }} ${{ steps.version.outputs.VERSION_LATEST }}.
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=${{ steps.version.outputs.VERSION_LATEST }}
            com.docker.extension.publisher-url=${{ env.PUBLISHER_WEBSITE }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
          file: ./${{ env.HUMAN_IMAGE_NAME }}/${{ steps.version.outputs.VERSION_SCHEME }}/Dockerfile
          context: ./Context
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          no-cache: true
          pull: true
          build-args: |
            JAVA_VERSION_MAJOR=${{ matrix.version }}
            JAVA_VERSION_LATEST=${{ steps.version.outputs.VERSION_LATEST }}

  dotnet:
    name: .NET
    runs-on: ubuntu-22.04
    needs: ubuntu
    env:
      REGISTRY_IMAGE_NAME: dotnet
      HUMAN_IMAGE_NAME: .NET
    strategy:
      matrix:
        version: [ '6.0', '7.0' ]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Fetch latest version
        id: version
        run: |
          DOTNET_VERSION=$(curl --silent "https://dotnetcli.azureedge.net/dotnet/Runtime/${{ matrix.version }}/latest.version")
          echo "DOTNET_VERSION=${DOTNET_VERSION}" >> $GITHUB_OUTPUT

      - name: Create metadata for Docker image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          flavor: latest=false
          images: ${{ env.REGISTRY_NAME }}/${{ github.repository_owner }}/${{ env.REGISTRY_IMAGE_NAME }}
          tags: type=raw,value=${{ matrix.version }}
          labels: |
            org.opencontainers.image.title=${{ env.HUMAN_IMAGE_NAME }} ${{ steps.version.outputs.DOTNET_VERSION }}
            org.opencontainers.image.description=My personal image for ${{ env.HUMAN_IMAGE_NAME }} ${{ steps.version.outputs.DOTNET_VERSION }}.
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=${{ steps.version.outputs.DOTNET_VERSION }}
            com.docker.extension.publisher-url=${{ env.PUBLISHER_WEBSITE }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
          file: ./${{ env.HUMAN_IMAGE_NAME }}/Dockerfile
          context: ./Context
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          no-cache: true
          pull: true
          build-args: |
            DOTNET_VERSION=${{ steps.version.outputs.DOTNET_VERSION }}

  aspnetcore:
    name: ASP.NET
    runs-on: ubuntu-22.04
    needs: ubuntu
    env:
      REGISTRY_IMAGE_NAME: aspnetcore
      HUMAN_IMAGE_NAME: ASP.NET
    strategy:
      matrix:
        version: [ '6.0', '7.0' ]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Fetch latest version
        id: version
        run: |
          ASPNETCORE_VERSION=$(curl --silent "https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/${{ matrix.version }}/latest.version")
          echo "ASPNETCORE_VERSION=${ASPNETCORE_VERSION}" >> $GITHUB_OUTPUT

      - name: Create metadata for Docker image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          flavor: latest=false
          images: ${{ env.REGISTRY_NAME }}/${{ github.repository_owner }}/${{ env.REGISTRY_IMAGE_NAME }}
          tags: type=raw,value=${{ matrix.version }}
          labels: |
            org.opencontainers.image.title=${{ env.HUMAN_IMAGE_NAME }} ${{ steps.version.outputs.ASPNETCORE_VERSION }}
            org.opencontainers.image.description=My personal image for ${{ env.HUMAN_IMAGE_NAME }} ${{ steps.version.outputs.ASPNETCORE_VERSION }}.
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=${{ steps.version.outputs.ASPNETCORE_VERSION }}
            com.docker.extension.publisher-url=${{ env.PUBLISHER_WEBSITE }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
          file: ./${{ env.HUMAN_IMAGE_NAME }}/Dockerfile
          context: ./Context
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          no-cache: true
          pull: true
          build-args: |
            ASPNETCORE_VERSION=${{ steps.version.outputs.ASPNETCORE_VERSION }}
